---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: streamarr-web CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container: node:26-alpine@sha256:aadf416b2cdce311a8811ba3f0608a61b77dbf997500e2eafe781b51f6a0b019
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install and Enable Corepack
        run: npm install -g corepack --force && corepack enable
      - name: Install dependencies
        env:
          CYPRESS_INSTALL_BINARY: '0'
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
